services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: sh -c "/auction"
    networks:
      - localNetwork

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    networks:
      - localNetwork

  test:
    image: golang:1.26.4
    working_dir: /app
    volumes:
      - .:/app
      - go-mod-cache:/go/pkg/mod
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    command: sh -c "go test -race ./... && go test -race -tags integration ./..."

volumes:
  mongo-data:
    driver: local
  go-mod-cache:
    driver: local

networks:
  localNetwork:
    driver: bridge